-

diff --git a/package/DEBIAN/postrm b/package/DEBIAN/postrm
--- a/package/DEBIAN/postrm
+++ b/package/DEBIAN/postrm
@@ -1,17 +1,17 @@
 #!/bin/bash
-set -e # fail on any error
-set -u # treat unset variables as errors
+set -e; # fail on any error
+set -u; # treat unset variables as errors
 
 # ======[ Trap Errors ]======#
-set -E # let shell functions inherit ERR trap
+set -E; # let shell functions inherit ERR trap
 
 # Trap non-normal exit signals:
 # 1/HUP, 2/INT, 3/QUIT, 15/TERM, ERR
-trap err_handler 1 2 3 15 ERR
+trap err_handler 1 2 3 15 ERR;
 function err_handler {
-    local EXIT_STATUS=${1:-$?}
-    logger -s -p "syslog.err" -t "ootync.deb" "supersh.deb script '$0' error code $EXIT_STATUS (line $BASH_LINENO: '$BASH_COMMAND')"
-    exit $EXIT_STATUS
+    local EXIT_STATUS=${1:-$?};
+    logger -s -p "syslog.err" -t "ootync.deb" "supersh.deb script '$0' error code $EXIT_STATUS (line $BASH_LINENO: '$BASH_COMMAND')";
+    exit $EXIT_STATUS;
 }
 
 echo "... Ваш код установочного скрипта ..."
