-

diff --git a/package/DEBIAN/preinst b/package/DEBIAN/preinst
--- a/package/DEBIAN/preinst
+++ b/package/DEBIAN/preinst
@@ -9,9 +9,9 @@ set -E # let shell functions inherit ERR trap
 # 1/HUP, 2/INT, 3/QUIT, 15/TERM, ERR
 trap err_handler 1 2 3 15 ERR
 function err_handler {
-    local exit_status=${1:-$?}
-    logger -s -p "syslog.err" -t "ootync.deb" "supersh.deb script '$0' error code $exit_status (line $BASH_LINENO: '$BASH_COMMAND')"
-    exit $exit_status
+    local EXIT_STATUS=${1:-$?}
+    logger -s -p "syslog.err" -t "ootync.deb" "supersh.deb script '$0' error code $EXIT_STATUS (line $BASH_LINENO: '$BASH_COMMAND')"
+    exit $EXIT_STATUS
 }
 
 echo "... Ваш код установочного скрипта ..."
